### ISSUE TITLE
Some feedback using Linux executable

### ISSUE THREAD

**Issue by sjx95** [momocow/HanaYome#2]
看大佬好像是臺灣人，就不用英語咯

README中提供的可執行文件包，在Linux下大部分工作正常，然而有幾個問題。

1. PepperFlash 目錄是空的，libpeppyflashplayer.so似乎並沒有被打包進去，因此進入遊戲後會提示Flash需要更新。我目前是把[poooi/poi](https://github.com/poooi/poi)中抽出來的二進制文件推進去了，運行正常。
2. zip導致文件權限異常混亂，比如用unzip解包後locales/之類的目錄權限爲644，electron因無法進入目錄，報錯缺少資源文件等，需要進行一些手工權限修復。如果條件許可建議使用tar的方式打包，這樣權限就被記錄進去了。

順帶一提代理真是關鍵功能啊，我就是因爲沒有代理功能才拖到現在才開始在Linux下面用www
目前是用iptables處理的，這個軟件小小的除了打開個Flash啥都沒有，蠻好用的。

**Comment by momocow** [comment]
首先感謝你的反饋，代理部分想跟你請教一下你的使用情境，也許會給我一些想法。整體軟件架構基本上參考poi的，透過本機代理獲取封包，以作為素材統計或其他延伸應用(目前尚未實現就是了orz)

關於那兩點提案：
1. 抱歉，下次會一併打包進去orz
基本上載入pepperflash的邏輯也是參照著poi去修改的這部分，程式首先會在系統路徑內尋找pepperflash，接著才尋找打包文件內附帶的版本。(系統內尋找pepperflash的演算法是交由eletron.app去處理的)
2. 下個版本會改變打包的方式。wincows平台改以nsis installer作為包裝，linux平台會以appImage作為包裝，並且使用像是travis這類ci服務器進行打包，希望屆時就沒這個問題。

**Comment by sjx95** [comment]
代理的话感觉支持SOCKS5和HTTP就足够了。[岛风go](https://daofeng.591mogu.com/)使用本地的HTTP代理，还有一些用户会用某种方式<del>（比如SSH）</del>在本地开一个SOCKS5代理。

因为我在Linux下用Chrome的，它自带了Flash，而且openSUSE的Flash的lib好像有点问题，我就没装那个库（逃

**Comment by momocow** [comment]
喔，好的，了解了。
謝謝OwO

**Comment by sjx95** [comment]
对了，希望能有个刷新按钮～

**Comment by momocow** [comment]
如果你說的是瀏覽器F5的功能, 理論上是有了阿... 
(上排工具列有個箭頭圍圈的符號
![refresh.jpg](https://github.com/momocow/HanaYome/blob/master/deprecated/assets/image/refresh.png?raw=true)

我明天再開個虛擬機看看linux是什麼情況Orz

**Comment by sjx95** [comment]
可能因为我正在用1.1.0alpha…

**Comment by momocow** [comment]
目前新版本在 linux 系統用 AppImage 打包, 不知道是否還有文件權限的問題?

**Comment by sjx95** [comment]
新版本前幾天就看到了，不過這週末有考試，就還沒碰。
主要是AppImage這種我沒碰過，不怎麼會用……

剛剛試了一下，啓動時出現了如下錯誤，大概是我的打開方式不正確？
考完試周天我再仔細研究下，複習線性系統理論去了（逃

---

```bash
~/src> ./hanayome-2.1.1-x86_64.AppImage                                                              
[Debug Mode]=false                                                                                                      

A JavaScript error occurred in the main process
Uncaught Exception:
Error: An error occurs when reading a language file. /tmp/.mount_hanayortZP7T/app/resources/assets/lang/en_US.lang.csonENOENT: no such file or directory, access '/tmp/.mount_hanayortZP7T/app/resources/assets/lang/en_US.lang.cson'
    at Object.fs.accessSync (fs.js:301:11)
    at Object.fs.accessSync (ELECTRON_ASAR.js:426:27)
    at Object.loadCSONFile (/tmp/.mount_hanayortZP7T/app/resources/app.asar/util/fs.js:1:321)
    at a.load (/tmp/.mount_hanayortZP7T/app/resources/app.asar/util/Dictionary.js:1:450)
    at new a (/tmp/.mount_hanayortZP7T/app/resources/app.asar/util/Dictionary.js:1:386)
    at Function.a.getDict (/tmp/.mount_hanayortZP7T/app/resources/app.asar/util/Dictionary.js:1:1066)
    at use (/tmp/.mount_hanayortZP7T/app/resources/app.asar/service/translating.js:1:793)
    at Object.initTranslating (/tmp/.mount_hanayortZP7T/app/resources/app.asar/service/translating.js:1:498)
    at Object.<anonymous> (/tmp/.mount_hanayortZP7T/app/resources/app.asar/index.js:1:638)
    at Object.<anonymous> (/tmp/.mount_hanayortZP7T/app/resources/app.asar/index.js:4:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/tmp/.mount_hanayortZP7T/app/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/tmp/.mount_hanayortZP7T/app/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
```

**Comment by momocow** [comment]
恩... 這科目聽起來不像是可以下飯的東西 :s

看樣子 AppImage 確實就是如你這麼開的, 因為這些訊息是我這邊輸出的xd
看來是我語系檔沒有放齊導致找不到en_US語系的檔案, 我只記得打包了繁體中文的, 
由於我現在是直接抓取系統語系, 然後搜尋對應的檔案, 
疏忽而沒考量找不到檔案時應該要使用預設語言
晚點放個 patch, 預設語言就指向繁體中文

**Comment by momocow** [comment]
看起來 AppImage 就是靠類似掛載硬碟的概念來啟動應用的(?
如果偏好用繁體, 不必設定直接啟動就可以了。

剛剛發布 v2.1.2 修補語言檔這一塊漏洞, 
程式會先由設定檔 **(註1)** 尋找使用者偏好語系, 
如果設定為空, 則使用系統語系。
接著判斷若使用的語系沒有語言檔 **(註2)** 
則一律使用繁體中文。

> 註1: 設定檔位於 環境變數 `$XDG_CONFIG_HOME` 所指向之位置 或是 `~/.config` 目錄下 之 `app-config.cson`。修改 `hanayome.lang` 欄位可以改變偏好的語言檔, 這個日後會做成UI介面, 欄位內容為語言檔檔名 (不含附檔名 `.lang.cson` 部分), 因此也可以自己寫語言檔xd

> 註2: 語言檔位於 `<HanaYome路徑>/resources/assets/lang/<語系>.lang.cson`

**Comment by sjx95** [comment]
考完了，應該不會掛，大概……
It works. 直接運行也能夠啓動了，界面風格也萌萌噠，AppImage效果拔羣。
弱弱的問一下，這個latest-linux.yml是幹嘛的？還有那個設置裏的記錄是幹嘛的？
-----> 傻傻的我

問題嘛，如果硬要說的話，能不能去掉每次啓動時的那個系統集成對話框？或者加個不再彈出的按鈕？
另外我覺得沒必要先檢查更新再啓動，先啓動遊戲，然後在新的線程中檢查更新會比較合理？

**Comment by momocow** [comment]
latest-linux.yml 是版本更新用的文件，我跟 poi 依賴一樣的版本更新套件，本地的應用檢查更新時會拉取 github 上的文件比對版本。紀錄是應用的輸出訊息，平常是錯誤等級的訊息才會輸出，設置裡面的紀錄，記錄檔目前是每日一個檔，非今日的紀錄會壓縮成一個檔，記錄檔保存期限為一個月。

系統集成對話框是說版本更新通知的那個？
設置→更新 裡面取消勾選可以免去啟動更新檢查，設置→關於 裡面可以有按鈕手動啟動檢查。至於怎麼樣才不擾民我再思考看看xd 看是不是改成每星期檢查一次就好這個機制(我似乎也沒辣麼勤奮 orz 哈哈哈

**Comment by sjx95** [comment]
更新已关。系统集成那个应该是启动弹出的给你添加快捷方式那个窗口吧，我回头找个图来吧。
目前已经抛弃1.1改用2.1.2了～

**Comment by sjx95** [comment]
![image](https://user-images.githubusercontent.com/18415916/33050815-d3b9e9a2-cea1-11e7-8541-3fff37f0be24.png)
